Add files via upload

diff --git a/milorad b/milorad
--- a/milorad
+++ b/milorad
@@ -1,146 +1,161 @@
-#!/bin/bash
-if test "$(realpath "$0")" = /usr/local/bin/milorad
-    then
-    subcmd="$1"
-    package="$2"
-    currentdir="$(pwd)"
-    ans="n"
-    cd /opt/milorad/ || exit
-    if test "$subcmd" != ""
-        then
-        if test "$subcmd" = "install"
-            then
-            if test "$package" != ""
-                then
-                if test "$package" = "gump-win" -o "$package" = "gump-windows"
-                    then
-                    echo "Are you sure that you wish to install GUMP for Windows? [Y/n]"
-                    read -rp " > " ans
+#!/bin/fish
+if test $EUID -ne 0 && test "$argv[1]" = "install" -o "$argv[1]" = "remove" -o "$argv[1]" = "update"
+    echo -e "\e[0;31mFatal: milorad cannot run as a standard user.\e[0m\nTry 'sudo milorad $argv[1] $argv[2]'."
+    exit
+end
+set currentdir "$(pwd)"
+set ans "n"
+cd /opt/milorad/ || exit
+if test "$argv[1]" != ""
+    if test "$argv[1]" = "install"
+        if test "$argv[2]" != ""
+            if test "$argv[2]" = "gump-dev"
+                if test -e GUMP-Development/
+                    echo -e "GUMP for developers is already installed\nDid you mean 'sudo milorad update $argv[2]'?\nTry 'milorad help' for more information."
+                else
+                    echo "Are you sure that you wish to install GUMP for developers? [Y/n]"
+                    read --prompt-str " > " ans
                     if test "$ans" = "Y" -o "$ans" = "y"
-                        then
-                        if test -e GUMP-Windows/
-                            then
-                            echo -e "GUMP for Windows is already installed\nDid you mean 'milorad update $package'?\nTry 'milorad help' for more information."
-                        else
-                            git clone https://github.com/milorad-co/GNU-Useless-Manipulation-Program
-                            cd GNU-Useless-Manipulation-Program/ || exit
-                            rm -rfv Linux/
-                            rm -rfv Development/
-                            mv -v Windows/ /opt/milorad/GUMP-Windows/
-                            cd /opt/milorad/ || exit
-                            rm -rfv GNU-Useless-Manipulation-Program
-                            touch gump-win
-                            echo -e "#!/bin/bash\nwine /opt/milorad/GUMP-Windows/GUMP.exe" > gump-win
-                            echo -e "\nThe GNU Useless Manipulation Program for Windows has been installed.\nIt can be found in the directory /opt/milorad/, but can also be started by entering the command 'gump-win', asumming that you have WINE installed."
-                            ans="n"
-                        fi
-                    fi
-                fi
-                if test "$package" = "gump-dev" -o "$package" = "gump-development"
-                    then
-                    echo "Sorry, the development build of GUMP is not available at the moment. It will be released in a few weeks."
-                fi
-                if test "$package" = "gump-deb" -o "$package" = "gump-linux" -o "$package" = "gump"
-                    then
-                    echo "Sorry, the Linux build of GUMP is not available at the moment. It will be released in a few weeks."
-                fi
-                if test "$package" != "gump-deb" -a "$package" != "gump-linux" -a "$package" != "gump" -a "$package" = "gump-dev" -a "$package" != "gump-development" -a "$package" != "gump-win" -a "$package" != "gump-windows"
-                    then
-                    echo -e "Invalid option: '$package'.\nTry 'milorad help' for more information."
-                fi
-            else
-                echo -e "Missing operand.\nTry 'milorad help' for more information"
-            fi
-        fi
-        if test "$subcmd" = "update" -o "$subcmd" = "reinstall"
-            then
-            if test "$package" != ""
-                then
-                if test "$package" = "gump-win" -o "$package" = "gump-windows"
-                    then
-                    if test -e /opt/milorad/GUMP-Windows/
-                        then
-                        rm -rfv /opt/milorad/GUMP-Windows/
                         git clone https://github.com/milorad-co/GNU-Useless-Manipulation-Program
-                        cd GNU-Useless-Manipulation-Program || exit
+                        cd GNU-Useless-Manipulation-Program/ || exit
                         rm -rfv Linux/
-                        rm -rfv Development/
-                        mv -v Windows/ /opt/milorad/GUMP-Windows/
+                        rm -rfv Windows/
+                        mv -v Development/ /opt/milorad/GUMP-Development/
                         cd /opt/milorad/ || exit
                         rm -rfv GNU-Useless-Manipulation-Program
-                        touch gump-win
-                        echo -e "wine /opt/milorad/GUMP-Windows/GUMP.exe" > gump-win
-                        echo -e "\nThe GNU Useless Manipulation Program for Windows has been updated."
-                    else
-                        echo -e "GUMP for Windows is not installed\nDo you want to install it? [Y/n]"
-                        read -rp " > " ans
-                        if test "$ans" = "Y" -o "$ans" = "y"
-                            then
-                            milorad install gump-win
-                        fi
-                    fi
-                fi
-                if test "$package" = "gump-dev" -o "$package" = "gump-development"
-                    then
+                        cd /usr/local/bin/ || exit
+                        touch gump-dev
+                        echo -e "#!/bin/bash\nopen /opt/milorad/GUMP-Development/GUMP.yyp" > gump-dev
+                        chmod -v a+x gump-dev
+                        echo -e "\nThe GNU Useless Manipulation Program for developers has been installed.\nIt can be found in the directory /opt milorad/, but can also be started by entering the command 'gump-dev', asumming that you have GameMaker installed."
+                        set ans "n"
+                    end
+                end
+            end
+            if test "$argv[2]" = "gump"
+                if test -e GUMP/
+                    echo -e "GUMP is already installed\nDid you mean 'sudo milorad update $argv[2]'?\nTry 'milorad help' for more information."
+                else
+                    echo "Are you sure that you wish to install GUMP? [Y/n]"
+                    read --prompt-str " > " ans
+                    if test "$ans" = "Y" -o "$ans" = "y"
+                        git clone https://github.com/milorad-co/GNU-Useless-Manipulation-Program
+                        cd GNU-Useless-Manipulation-Program/ || exit
+                        rm -rfv Windows/
+                        rm -rfv Development/
+                        mv -v Linux/ /opt/milorad/GUMP/
+                        cd /opt/milorad/ || exit
+                        rm -rfv GNU-Useless-Manipulation-Program
+                        cd /opt/milorad/GUMP/ || exit
+                        chmod -v a+x GUMP
+                        cd /usr/local/bin/ || exit
+                        touch gump
+                        echo -e "#!/bin/bash\n/opt/milorad/GUMP/GUMP" > gump
+                        chmod -v a+x gump
+                        echo -e "\nThe GNU Useless Manipulation Program has been installed.\nIt can be found in the directory /opt/milorad/, but can also be started by entering the command 'gump'."
+                        set ans "n"
+                    end
+                end
+            end
+            if test "$argv[2]" != "gump" -a "$argv[2]" != "gump-dev"
+                echo -e "Invalid option: '$argv[2]'.\nTry 'milorad help' for more information."
+            end
+        else
+            echo -e "Missing operand.\nTry 'milorad help' for more information"
+        end
+    end
+    if test "$argv[1]" = "update"
+        if test "$argv[2]" != ""
+            if test "$argv[2]" = "gump-dev"
+                if test -e /opt/milorad/GUMP-Development/
+                    rm -rfv /opt/milorad/GUMP-Development/
+                    git clone https://github.com/milorad-co/GNU-Useless-Manipulation-Program
+                    cd GNU-Useless-Manipulation-Program || exit
+                    rm -rfv Linux/
+                    rm -rfv Windows/
+                    mv -v Development/ /opt/milorad/GUMP-Development/
+                    cd /opt/milorad/ || exit
+                    rm -rfv GNU-Useless-Manipulation-Program
+                    cd /usr/local/bin/ || exit
+                    touch gump-dev
+                    echo -e "#!/bin/bash\nopen /opt/milorad/GUMP-Development/GUMP.yyp" > gump-dev
+                    chmod -v a+x gump-dev
+                    echo -e "\nThe GNU Useless Manipulation Program for developers has been updated."
+                else
                     echo -e "GUMP for developers is not installed\nDo you want to install it? [Y/n]"
-                    read -rp " > " ans
+                    read --prompt-str " > " ans
                     if test "$ans" = "Y" -o "$ans" = "y"
-                        then
-                        milorad install gump-dev
-                    fi
-                fi
-                if test "$package" = "gump-deb" -o "$package" = "gump-linux" -o "$package" = "gump"
-                    then
-                    echo -e "GUMP for Linux is not installed\nDo you want to install it? [Y/n]"
-                    read -rp " > " ans
+                        sudo milorad install gump-dev
+                    end
+                end
+            end
+            if test "$argv[2]" = "gump"
+                if test -e /opt/milorad/GUMP/
+                    rm -rfv /opt/milorad/GUMP/
+                    git clone https://github.com/milorad-co/GNU-Useless-Manipulation-Program
+                    cd GNU-Useless-Manipulation-Program || exit
+                    rm -rfv Windows/
+                    rm -rfv Development/
+                    mv -v Linux/ /opt/milorad/GUMP/
+                    cd /opt/milorad/ || exit
+                    rm -rfv GNU-Useless-Manipulation-Program
+                    cd /opt/milorad/GUMP/ || exit
+                    chmod -v a+x GUMP
+                    cd /usr/local/bin/ || exit
+                    touch gump
+                    echo -e "#!/bin/bash\n/opt/milorad/GUMP-Windows/GUMP.exe" > gump-win
+                    chmod -v a+x gump
+                    echo -e "\nThe GNU Useless Manipulation Program has been updated."
+                else
+                    echo -e "GUMP is not installed\nDo you want to install it? [Y/n]"
+                    read --prompt-str " > " ans
                     if test "$ans" = "Y" -o "$ans" = "y"
-                        then
-                        milorad install gump
-                    fi
-                fi
-                if test "$package" != "gump-deb" -a "$package" != "gump-linux" -a "$package" != "gump" -a "$package" = "gump-dev" -o "$package" = "gump-development" -a "$package" = "gump-win" -a "$package" = "gump-windows"
-                    then
-                    echo -e "Invalid option: '$package'.\nTry 'milorad help' for more information."
-                fi
-            else
-                rm -rfv "$(realpath "$0")"
-                git clone https://github.com/milorad-co/milorad-installer/
-                cd milorad-installer/ || exit
-                chmod +x milorad.sh
-                sudo ./milorad.sh
-                cd ..
-                rm -r milorad-installer/
-                echo -e "\nThe Milorad Application Installer has been updated."
-            fi
-        fi
-        if test "$subcmd" = "remove"
-            then
-            if test "$package" != ""
-                then
-                if test "$package" = "gump" -o "$package" = "gump-deb" -o "$package" = "gump-linux"
-                    then
+                        sudo milorad install gump
+                    end
+                end
+            end
+            if test "$argv[2]" != "gump" -a $argv[2] != "gump-dev"
+                echo -e "Invalid option: '$argv[2]'.\nTry 'milorad help' for more information."
+            end
+        else
+            rm -rfv "$(status -f)"
+            git clone https://github.com/milorad-co/mai-config/
+            cd mai-config/ || exit
+            chmod a+x milorad-setup.sh
+            ./milorad-setup.sh
+            cd ..
+            rm -r milorad-installer/
+            /opt/milorad/mai-config/latest-versions.sh
+            echo -e "\nThe Milorad Application Installer has been updated."
+        end
+    end
+    if test "$argv[1]" = "remove"
+        if test "$argv[2]" != ""
+            if test "$argv[2]" = "gump"
+                if test -e /opt/milorad/GUMP/
+                    rm -rfv /opt/milorad/GUMP/
+                    echo -e "\nGUMP has been removed."
+                else
                     echo "GUMP was not installed, so not removed."
-                fi
-                if test "$package" = "gump-dev" -o "$package" = "gump-development"
-                    then
+                end
+            end
+            if test "$argv[2]" = "gump-dev"
+                if test -e /opt/milorad/GUMP-Development/
+                    rm -rfv /opt/milorad/GUMP-Development/
+                    echo -e "\nGUMP for development has been removed."
+                else
                     echo "GUMP for development was not installed, so not removed."
-                fi
-                if test "$package" = "gump-win" -o "$package" = "gump-windows"
-                    then
-                    if test -e /opt/milorad/GUMP-Windows/
-                        then
-                        rm -rfv /opt/milorad/GUMP-Windows/
-                        echo -e "\nGUMP for Windows has been removed."
-                    else
-                        echo "GUMP for Windows was not installed, so not removed."
-                    fi
-                fi
-            fi
-        fi
-        if test "$subcmd" = "help"
-            then
-            echo "Milorad Application Installer (M.A.I.)
-Usage: sudo milorad <subcommand> <application>
+                end
+            end
+            if test "$argv[2]" != "gump" -o "$argv[2]" != "gump-dev"
+                echo "Invalid option: '$argv[2]'.\nTry 'milorad help' for more information."
+            end
+        end
+    end
+    if test "$argv[1]" = "help"
+        echo "Milorad Application Installer (M.A.I.) Version 1
+Usage: sudo milorad <install/remove/update> <application>
+   or: milorad help
 
 Milorad Application Installer (M.A.I.) is a commandline Milorad application manager and
 provides commands for installing, removing, and updating all Milorad appliations, such
@@ -150,23 +165,16 @@ Subcommands
 help               display this help
 install            install an application
 remove             remove an installed application
-update/reinstall   remove an installed application (or this installer if no application
-                   name is provided) then install the latest version of that application
+update             replace an installed application (or this installer if no application
+                   name is provided) with the latest version
 Applications
 gump               a useless art program
-gump-dev           the developer beta of gump, for use with gamemaker
-gump-win           the windows version of gump"
-        fi
-        if test "$subcmd" != "install" -a "$subcmd" != "update" -a "$subcmd" != "remove" -a "$subcmd" != "help"
-            then
-            echo -e "Invalid option: '$subcmd'.\nTry 'milorad help' for more information."
-        fi
-    else
-        echo -e "Missing operand.\nTry 'milorad help' for more information."
-    fi
-    cd "$currentdir" || exit
+gump-dev           the developer prerelease of gump, for use with gamemaker"
+    end
+    if test "$argv[1]" != "install" -a "$argv[1]" != "update" -a "$argv[1]" != "remove" -a "$argv[1]" != "help"
+        echo -e "Invalid option: '$argv[1]'.\nTry 'milorad help' for more information."
+    end
 else
-    mv -fv "$(realpath "$0")" /usr/local/bin/milorad
-    mkdir -pv /opt/milorad/
-    echo "The Milorad Application installer has been set up. Run the command 'milorad help' for general help."
-fi
+    echo -e "Missing operand.\nTry 'milorad help' for more information."
+end
+cd "$currentdir" || exit
